services:
  db:
    image: postgres:15
    container_name: sgw_db
    restart: always
    env_file:
      - .env  # .env 파일을 사용하여 환경 변수 설정
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data


  api:
    build: .
    container_name: sgw_service
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  pg_data:
